### ISSUE TITLE
Cedulky na dokumentaci trosek

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#10]
Do vybavení auta by bylo vhodné přidat vhodné cedulky pro označování trosek. 
Konstrukce cedulek by měla umožnit jejich umístění v různém terénu. Zároveň by cedulky měly být dobře viditelné, aby na ně někdo při hledání dalších trosek nešlápl. 
Identifikace cedulky by měla být z fotografie dobře čitelná.

**Comment by raska-vilem** [comment]
Ty cedulky mají mít svoje číslo už v 3D modelu, nebo se dodělá až na vytištěném modelu?

**Comment by kaklik** [comment]
Záleží, jakým způsobem by se mělo na modelu pak dodělávat. Cílem je mít s tím co nejmíň práce.

**Comment by kaklik** [comment]
Vidím, že jsi navrhunul tohle: 
![obrazek](https://user-images.githubusercontent.com/1194177/54742828-b5f54700-4bc2-11e9-8339-44596d32899a.png)

Jak se to ale použije na asfaltové dráze? A jak se označí jednotlivé díly? 

![troska](https://user-images.githubusercontent.com/1194177/54742993-30be6200-4bc3-11e9-9d93-56b7d6537484.JPG)
