### ISSUE TITLE
Krabička pro vnitřní zásuvky

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#12]
Krabička může vycházet z [této verze](https://github.com/expediceupice/Raketa/tree/master/3Dprint/igniter), kterou navrhoval původně @ChroustJan 

Akorát je potřeba, aby matice pro upevnění víčka byly zasouvány do kapes z vnější strany krabičky. 

[Zásuvky](https://www.tme.eu/cz/details/procar-57612003/automobilove-napajeci-prislusenstvi/pro-car/57612003/), které mají do krabičky pasovat.

**Comment by kaklik** [comment]
Všiml jsem si, že jsi již nahrál soubory s návrhem krabičky. Díval jsem se na ně a je fajn, že jsi to udělalal, mám k nim ale několik připomínek. 

Je potřeba soubory pojmenovat názvy, které neobsahují diakritiku a mezery. Tyto znaky dělají potíže při automatickém zpracování souborů. 

Na samotné krabičce pak vidím tyto potíže

- Krabička nepůjde dobře vytisknout, protože kapsy pro matky nemají  na rozdíl od vzorové krabičky šikmý náběh a tisknou se rovnou do vzduchu. Otvory pro matky jsou konstruovány tak, že matky se musí vkládat z vnitřní strany krabičky. Toto je konstrukční chyba i u vzorové krabičky, neboť matky během šroubování víčka vypadávají. Lepší by bylo je vkládat zvenku. 

Model který vidím vypadá takto:
![image](https://user-images.githubusercontent.com/1194177/55077098-3c17fe80-5097-11e9-80fd-938aaf12235b.png)

Vzorová krabička má šikmý náběh ke kapsám pro matky, právě kvůli usnadnění tisku: 

![image](https://user-images.githubusercontent.com/1194177/55077352-d11af780-5097-11e9-876b-4516d44c8986.png)


-  Do svorky pro vodiče nepůjdou vodiče vložit zboku, protože svorka objímá více než polovinu průřezu vodiče. 
![image](https://user-images.githubusercontent.com/1194177/55077172-5eaa1780-5097-11e9-9e66-28a54f1d7017.png)


-  Na gitu je také soubor viko.scad, který ale je efektivně prádný, takže tam zřejmě nemusí být.

**Comment by JakubMares96** [comment]
Aktuální podoba:
![image](https://user-images.githubusercontent.com/48317171/55472154-a850b000-560b-11e9-867e-3a136cfec508.png)

![image](https://user-images.githubusercontent.com/48317171/55472206-cae2c900-560b-11e9-97b9-83757f7311ad.png)

**Comment by kaklik** [comment]
Ve skutečném výtisku jsou tyto chyby: 

- Sloupky pro víčko doléhají k modelu jen z jedné strany
- Víčko je jinak tlusté než zbytek krabičky. (tlouška krabičky by měla být sjednocená parametrem wall_thickness)
-  svorky  přívodů předpokládají různý průměr průměr vodiče (průměr na krabičce se liší od průměru na stahovacím dílu)
- Zahloubení pro hlavu šroubu na víčku komplikuje tisk. Podobně i zahloubení na stahovacích svorkách, neboť se pak otvor pro šroub netiskne už od podložky.

**Comment by roman-dvorak** [comment]
Model má řadu problémů:

- Otvor na zásuvky je moc úzký. Musí být širokvý 71 mm.
- Rozteče děr na přišroubování desky se zásuvkamy je špatný. Správné rozteče děr jsou 82 x 22 mm
- Otvory pro šrouby skrze panel mají divný rozměr - je potřeba použít správné parametry `M3_screw_diameter`
- Matka se v díře protáčí `M3_nut_diameter`
- V krabičce, kde se mají přišroubovat kabely je potřeba vložit matky do kapsy. Aktuální způsob je velmi složité na složení. A pokud v krabičce budou už namontovány zásuvky, tak je to skoro nesestavitelné.

Na svorce na kabely jsou špatné velikosti válců na kabely.

**Comment by roman-dvorak** [comment]
Další problémy jsou, že do víčka nelze zapustit hlavička šroubu - je moc malá díra. To samé platí o svorkách na kabel. 

Pak sloupky pro šrouby v krabičci jsou kus od stěny.

![20190706_104232](https://user-images.githubusercontent.com/5196729/60754017-73257680-9fdb-11e9-8300-27fcb0a9c276.jpg)

![20190706_104126](https://user-images.githubusercontent.com/5196729/60754024-7d477500-9fdb-11e9-90bc-9e0f20d445a8.jpg)

![20190706_104113](https://user-images.githubusercontent.com/5196729/60754026-820c2900-9fdb-11e9-9f96-ab122b62c329.jpg)

**Comment by JakubMares96** [comment]
Tyto problémy vznikly asi tím, že vytištěný model nebyl aktuální nahranou verzí. (již 3 měsíce)
Další věc  se týká zapuštění šroubů. @kaklik, při posledním tisku, na tento problém narazil a měl připomínku "Zahloubení pro hlavu šroubu na víčku komplikuje tisk. Podobně i zahloubení na stahovacích svorkách, neboť se pak otvor pro šroub netiskne už od podložky.". Teď nevím, zda tam to zahloubení dát či ne? 

Do tohoto modelu se má přidat navíc ukazatel napětí a nevím, kam ho umístit. Vedle konektorů, nebo z nějakého boku?  To se asi rozhodne podle toho, jak bude krabička umístěna v autě.

**Comment by roman-dvorak** [comment]
Ano, to zahloubení tam má být. Ve víčku určitě. A nad hlavu šroubu vynecháš jednu plnou vrstvu. Stejnak jako jsem Ti psal v chatu o plné vrstvě nad kapsou pro matku. 

Ano, navrhuji posunout otvor pro zásuvky excentricky a otvor pro měřák napětí umístit vedle toho. 

Můžeš sem, prosím, dát odkazy na STL soubory, které to jsou.

**Comment by roman-dvorak** [comment]
@JakubMares96 prohlížel jsem si teď ty Tvé modely - ve víčku je určitě špatně nastavená velikost díry pro zapuštění hlavy šroubu. Je nějaký důvodu, že si to počítáš sám (špatně) a nepoužíváš připravený parametr?

Také jsou špatně nastaveny cesty k parametrickému souboru. Proto to vůbec nefunguje.

Jinak např. průměr vodičů, které tam jsou, navrhuji přesunout do parametrického souboru. Aby to  bylo pouze na jednom místě. 

z jakého důvodu kód obsahuje tyto části:

`cylinder(h=M3_nut_height,d=M3_nut_diameter*1.1,$fn=6);`
`M3_nut_diameter*0.9,M3_nut_height*1.2`

Ty parametry jsou nastavené tak, že když se vytisknout, tak jejich hodnota sedí s těmi šrouby.

**Comment by JakubMares96** [comment]
Nahrál jsem upravenou verzi. 
+přidání záslepek pro tisk

![image](https://user-images.githubusercontent.com/48317171/61132780-5944d180-a4bc-11e9-80d5-e31f9b5861cf.png)

![image](https://user-images.githubusercontent.com/48317171/61132800-6497fd00-a4bc-11e9-812e-befc350fcf53.png)

**Comment by kaklik** [comment]
Poslední vytištěná krabička má nekonzistentní tloušťku stěn.  Dno je jinak tlusté, než stěny a stěny jsou zřejmě příliš tenké. 
V oblasti víčka jsou dokonce tak, tenké, že slicer tuto část ani netiskne.

Není mi také jasná nutnost tloušťky víčka. Víčko je vzhledem ke krabičce úplně neúměrně tlusté a tiskne se díky tomu asi 8 hodin. 

![obrazek](https://user-images.githubusercontent.com/1194177/61393146-a19b2f80-a8c0-11e9-98b6-84e4b3c942c2.png)

**Comment by roman-dvorak** [comment]
U krabičky se objevilo několik dalších problémů, které je potřeba vyřešit:

- [ ] Voltmetr se nevejde do otvoru. (obrázky níže) @JakubMares96 můžeš mi prosím poslat odkaz na část kódu, kde se nastavuje velikost otvoru? A kde jsi získal tyto rozměry?

- [ ] Nové krabičce chybí vnější límec - víčko v ní tedy není zapuštěné jako u starší verze. 


### Rozměry voltmetru
![20190720_172556](https://user-images.githubusercontent.com/5196729/61584699-abd15e00-ab4c-11e9-9131-274f39ffa407.jpg)

![20190720_172618](https://user-images.githubusercontent.com/5196729/61584701-af64e500-ab4c-11e9-89a1-90894f9d3d8b.jpg)

![20190720_172707](https://user-images.githubusercontent.com/5196729/61584703-b2f86c00-ab4c-11e9-8fe5-12276ad80d62.jpg)

### Aktuální stav
![20190720_172420_HDR](https://user-images.githubusercontent.com/5196729/61584707-de7b5680-ab4c-11e9-882d-e6ecaf1d3afc.jpg)

![20190720_172318](https://user-images.githubusercontent.com/5196729/61584708-e20edd80-ab4c-11e9-9d0a-cfada5490fb6.jpg)

### Chybějící límec
![20190720_173217](https://user-images.githubusercontent.com/5196729/61584721-0bc80480-ab4d-11e9-825f-943ca1019037.jpg)

![20190720_173154](https://user-images.githubusercontent.com/5196729/61584723-108cb880-ab4d-11e9-9987-6e04d7d61460.jpg)

![20190720_173125](https://user-images.githubusercontent.com/5196729/61584724-1387a900-ab4d-11e9-9f62-bab0060ea30d.jpg)

**Comment by roman-dvorak** [comment]
Rozměry celé krabičky lze zmenšit. Délku bych udělal tak, nová délka odpovídala vzdálenosti dvou krajních výztuh. Výška krabičky stačí cca 6-7cm. Výsledkem bude, že se bude tisknout rychleji a v autě nebude zabírat tolik místa.

**Comment by JakubMares96** [comment]
Chybějící límec vznikl asi ve sliceru (moc tenká stěna) -> Ozkoušeno nyní by to mělo být OK.

Chyba u otvoru pro voltmer nevím čím mohla vzniknout. Tyto rozměry byli využity:
//vyrez pro voltmetr
translate([0,boxwidth/5,-boxheight/2])
cube([45.12,25.9,thicknesswall+5],center=true);

@roman-dvorak Mohu poprosit o změření rozměrů na vytištěném modelu?

**Comment by kaklik** [comment]
Vytištěný model nemáme k dispozici.  Tloušťka stěny musí být alespoň 0.61mm jinak se nevytiskne.

**Comment by roman-dvorak** [comment]
> //vyrez pro voltmetr
> translate([0,boxwidth/5,-boxheight/2])
> cube([45.12,25.9,thicknesswall+5],center=true);

No, je potřeba k tomu připočítat nějaké tolerance. Odkud vychází to číslo `45.12`? Když jsem naměřil délku `45.08 mm` tak bych nastavil něco klidně jako `45.08 + 1`. Vzhledem k velikosti límce voltmetru není problém přidat i o trochu více např 1.5 mm. 

To samé platí i o šířce `25.8 + 1.5 mm`.

Ten límec bych udělal určitě silnější než 1 vrstvu. Navrhuji `0.8 - 1 mm`. Stěnu takto velké krabičky cca `2 mm`.

**Comment by JakubMares96** [comment]
Akorát jsem odevzdal upravenou verzi. Podíváte se, prosím, ve sliceru s Aktuálním nastavením tisku zda je vše OK?

**Comment by kaklik** [comment]
Já jako nevím, ale můžeš mi @JakubMares96 vysvětlit, jak když je parametr nastavený takhle:
voltmetr_cutoutwidth = 22.3; 

Tak jak se tam může vejít volmetr, který má šuplerou změřenou šířku 29.19 mm ?

Takováhle práce je úplně k ničemu.

**Comment by kaklik** [comment]
Krabička doupravena vrtačkou.
