### ISSUE TITLE
Základna šestiosé platformy

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TF-R1#14]
Pro pneumatické válce [šestiosé platformy](https://github.com/ThunderFly-aerospace/TF-R1/issues/16) potřebujeme vytvořit držák, který bude určený pro přichycení na střechu vozidla (na hnědou desku z fotografie). Na pohyblivé části pak bude elektronický magnet, pro přichycení UAV. Horní díl je řešen v [jiném issue](https://github.com/ThunderFly-aerospace/TF-R1/issues/17).

Předchozí realizace montáže UAV vypadala takto:
![20190209_155119](https://user-images.githubusercontent.com/1194177/56282401-60538200-610f-11e9-99b7-e143e2437d01.jpg)

Aby v hnědé desce na střeše vozidla nebylo potřeba vrtat nové otvory, tak je nutné zachovat úchytné šrouby původního dílu [888_3009](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/888_3009.stl).

Hrubý náčrtek možného řešení:
![image](https://user-images.githubusercontent.com/9783606/57831787-5aa49700-77b6-11e9-8dee-21993db79702.png)

Prostřední díl válec a trojice ramen s otvory pro uchycení ložisek [EFOM-10](https://www.igus.cz/info/spherical-bearings-efom)(nutno vybrat typ z nabídky). Plocha pod ložisky musí jít parametricky naklápět ve dvou osách, aby bylo možné upravit rozsah pohybu v daném ložisku. Při změně parametrů se předpokládá přetištění dílu.

Existující držák, který je vidět na násludujících obrázcích má zdrojové kódy zde:
https://github.com/ThunderFly-aerospace/TF-R1/blob/master/CAD/src/platform/888_4003.scad
https://github.com/ThunderFly-aerospace/TF-R1/blob/master/CAD/src/platform/888_4004.scad

Základna platformy musí mít tyto vlastnosti:

- Je potřeba jí parametricky umět zvětšovat
- Musí být dělitelná na menší díly, aby jí bylo možné tisknout na tiskárně o maxímálním tiskovém rozměru 150mm
- Jednotlivé díly mmusí jít spojovat pomocí šroubů
- Musí být možné jedním parametrem nastavit poloměr vzdálenosti středu ložiska od osy procházející středem základny
- Dalšími parametry jsou dva úhly definující naklonění ložisek ve dvou osách (směrem do středu a do stran)

**Comment by kaklik** [comment]
Horní část základny stejná nebude, neboť je nutné, aby na horní části držela příruba elektropermanentního magnetu. Která se uchycuje 4mi šrouby. Což znamená, že horní díl musí být uzpůsoben k uchycení válce uprostřed. Použití příruby je vidět na této fotografii 

![20190209_155119](https://user-images.githubusercontent.com/1194177/56282401-60538200-610f-11e9-99b7-e143e2437d01.jpg)

[Díl na který je příruba uchycena](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/888_3006.stl)

Taktéž spodní díl by měl být uzpůsobený tomu, že bude ke střeše uchycen na již existující 4 otvory pro šrouby, jejichž vzdálenosti jsou patrné ze stejného dílu, na který je uchycena přiruba.

**Comment by JakubMares96** [comment]
![zakladna navrh](https://user-images.githubusercontent.com/48317171/56382944-e4ddf780-6218-11e9-9934-e2b18ec98413.png)

**Comment by kaklik** [comment]
Souhlasím, jen pokud horní část základny bude menší než ta spodní, tak bude ještě potřeba, aby ložiska byla nakloněná i dovnitř.

**Comment by JakubMares96** [comment]
@kaklik  @ChroustJan 
Návrh nohy pro připojení ložisek![image](https://user-images.githubusercontent.com/48317171/56854347-48f96d80-6935-11e9-919e-6f2c932d6a74.png)

![image](https://user-images.githubusercontent.com/48317171/56854358-747c5800-6935-11e9-8824-5096ad6186fa.png)

Středová část
![image](https://user-images.githubusercontent.com/48317171/56854374-b73e3000-6935-11e9-8d30-b4951a21c9ab.png)

**Comment by kaklik** [comment]
Já ty díly nemůžu na gitu nikde najít. 
Jsou určitě pushnuté?  Hledám je tady: https://github.com/ThunderFly-aerospace/TF-R1/tree/master/CAD/src

Ale co vidím z obrázků: 

- Není mi jasné, proč je tam ten úzký zbytek materiálu mezi ložisky. 
- U připevnění ložisek by mi asi přišlo logičtější, aby otvor na šroub měl ze spodni strany šestihran. Kulové ložisko by se pak k podložce montovalo tak, že se přitáhne maticí ke šroubu, který bude zespodu strčený do podložky. Matice se pak dotáhne klíčem.  V případě jak je to konstruované teďko mi není jasné, jak by bylo možné ten šroub dotáhnout bez sundání celé platformy. 
- Nerozumím funkci otvorů pro šrouby spojující jednotlivé díly. Na společné základně uprostřed chápu, že jsou asi matice. Ale pak mi není jasné, jakým způsobem se dostanou šrouby do dílu s ložisky.

**Comment by ChroustJan** [comment]
Horní část základny stejná nebude, neboť je nutné, aby na horní části držela příruba elektropermanentního magnetu. Která se uchycuje 4mi šrouby. Což znamená, že horní díl musí být uzpůsoben k uchycení válce uprostřed. Použití příruby je vidět na této fotografii

![](https://user-images.githubusercontent.com/1194177/56282401-60538200-610f-11e9-99b7-e143e2437d01.jpg)

Díl na který je příruba uchycena

Taktéž spodní díl by měl být uzpůsobený tomu, že bude ke střeše uchycen na již existující 4 otvory pro šrouby, jejichž vzdálenosti jsou patrné ze stejného dílu, na který je uchycena přiruba.

**Comment by ChroustJan** [comment]
Souhlasím, jen pokud horní část základny bude menší než ta spodní, tak bude ještě potřeba, aby ložiska byla nakloněná i dovnitř.

**Comment by ChroustJan** [comment]
Návrh nohy pro připojení ložisek
![](https://user-images.githubusercontent.com/48317171/56854347-48f96d80-6935-11e9-919e-6f2c932d6a74.png)


![](https://user-images.githubusercontent.com/48317171/56854358-747c5800-6935-11e9-8824-5096ad6186fa.png)
Středová část

![](https://user-images.githubusercontent.com/48317171/56854374-b73e3000-6935-11e9-8d30-b4951a21c9ab.png)

**Comment by ChroustJan** [comment]
- [x] U připevnění ložisek by mi asi přišlo logičtější, aby otvor na šroub měl ze spodni strany šestihran. Kulové ložisko by se pak k podložce montovalo tak, že se přitáhne maticí ke šroubu, který bude zespodu strčený do podložky. Matice se pak dotáhne klíčem. V případě jak je to konstruované teďko mi není jasné, jak by bylo možné ten šroub dotáhnout bez sundání celé platformy.

- [ ] Nerozumím funkci otvorů pro šrouby spojující jednotlivé díly. Na společné základně uprostřed chápu, že jsou asi matice. Ale pak mi není jasné, jakým způsobem se dostanou šrouby do dílu s ložisky.

**Comment by roman-dvorak** [comment]
Díly z obrázků jsou v podsložce [/CAD/src/platform](https://github.com/ThunderFly-aerospace/TF-R1/tree/master/CAD/src/platform) Už mají opravené některé chyby (oproti obrázkům), které popisuješ.

**Comment by ChroustJan** [comment]
@JanKott bylo by dobré, kdyby úchytná část pro ložisko byla měnitelným dílem, aby v případě potřeby změnit úhly nebylo potřeba tisknout příliš materiálu.

Možná by bylo vhodné mít 3 typy dílů. Středový, ramena (půjdou případně přidávat) a díl pro uchycení ložiska.

**Comment by JanKott** [comment]
Vytvořil jsem prvotní verzi základny v souborech 888_4003, 4004 a 4006.
Modely includují soubor calculations.scad, který obsahuje výpočty pro získání úhlů pístů a výšku horní platformy. Ze souboru to možná neni uplně jasné, takže můžu v případě potřeby vyrobit nějaký obrázek, kde bude alespoň vidět které trojúhelníky počítám a jak je značím.

**Comment by kaklik** [comment]
Vidím, že tam je hodně konstrukčních zlepšení.  

![888_4006](https://user-images.githubusercontent.com/1194177/58384594-b4d9ff00-7fe3-11e9-9fdc-e209f8afcca5.png)


Zřejmě ale chybí díra, pro matku, která přečnívá z pneumatického válce.  

Mezi ložisky vidím takový podivný útvar, není mi jasné, jak to vzniká. 

![888_4006](https://user-images.githubusercontent.com/1194177/58384584-9542d680-7fe3-11e9-9b75-6d572265550d.png)

Potom konstrukčně to chápu tak že na prostřední kruhovou část jsou jedním šroubem přišroubovány prodlužovací díly a k těmto dílům přes jeden šroub přišroubovány patky pístů. 

Nejsem si jistý, jestli jeden šroub je dostatečný, pravděpodobně by tam měla být spíš dvojice, aby celé prodloužení nemohlo být zkrouceno okolo jednoho šroubu.  Taktéž mi  nepřijde praktické, aby přístup ke šroubu byl přes celou délku modelu. Protože to pak vyžaduje použití extra dlouhéko inbus klíče. 
Praktičtějši by bylo, kdyby šrouby byly šikmo a přístup k jejich hlavě by byl  šikmo vrchní strany.

**Comment by JanKott** [comment]
Díru pro matku pneumatického válce doplnim podle původního modelu (z nějakýho důvodu to je "M6_nut_diameter + 3").

Podivný útvar mezi ložisky je způsoben tim, že ořezávám rameno, kulatou základnu a půlku držáku na písty v půlce. Držák na písty jsem ořízl moc daleko. Myslim, že to nemá to vliv na funkci, ale opravim to.

Šrouby zdvojim a otočim asi až zítra (ale trochu si vymejšlíš :-) ).

**Comment by JanKott** [comment]
FYI: abyste to nemuseli hledat - pro upevnění ložiska jsem zvolil šrouby M4 a pro spojování dílů M8x60.

**Comment by kaklik** [comment]
Já vim že si vymejšlim, ale šroub M8x60 je něco, co jinak vůbec nikde nepoužijem. Navíc je to předimenzovaný. Myslím ze bez problému bude stačit 2x šroub M4. Třeba 35mm dlouhý.

**Comment by JanKott** [comment]
Tak jsem předělal šrouby M8x60 na M4x35, zdvojil jsem je a natočil nahoru.

**Comment by kaklik** [comment]
Tak to pasuje :)

![zakladna](https://user-images.githubusercontent.com/1194177/58519731-1d2c0a80-81b5-11e9-94f8-bffbcfbf8eac.JPG)

Akorát šrouby pro přišroubování přírubového ložiska k základně by zřemě měly být M5. 
A díra pro přečnívající matku z přírubového ložiska musí být ještě větší, měřením vychází tak na 19.5mm.

**Comment by JanKott** [comment]
M4 šrouby jsem vyměnil za M5 a díru na přečnívající matku zvětšil na 19.5mm + global_clearance.

**Comment by JanKott** [comment]
Vytvořil jsem dvě knihovny pro zpřehlednění kódu:
1) bolts, která obsahuje modul bolt(size = 4, length = 35, pocket = true, pocket_size = 35, washer = false, square_nut = false)

Čili bez parametru bolt() vyrobí M4x35 šroub s maticí, s přesahem pro šroub a kapsou na matici.
Parametry washer a square_nut zatim nefungují, až je někdo bude potřebovat tak ať si je naimplementuje :-)
Kdo neznal funkci search, doporučuju se podívat na použití tabulky bolts a následného dohledání parametrů šroubu v listu listů.

2) print, která obsahuje balast co normálně dávám na konec modulu print(draft = true, position = [0, 0, 0], rotation = [0, 0, 0])

Je tam hezky vidět použití childů, vezme první child jako model co chci tisknout, druhý a další jako okolí modelu (assembly) a poslední jako výřezovou kostku. Parametry určují pozici a rotaci modelu pro tisk.

čili bez parametru:
print(draft)
{
  model();
  jiny_model();
  cube(10);
}

vytiskne v draftu model, černou barvou průhledně jiny_model a vyřízne z toho kostku 10x10x10.
Pokud je draft = false tak vytiskne jen model v pozici pro tisk.

Pokud jsou childy jen 2, pak nehledá assembly vizualizace.
Pokud je child jen 1, pak nehledá ani výřezovou kostku.

**Comment by kaklik** [comment]
Tyhle nový knihovny jsou docela pokrok! :) 

Jinak u té základny je ještě mírná komplikace v tom, že ty šrobouvé spoje mě překvapily v tom, že jak jsou šikmo, tak každý spojený díl je trochu přizvednutý. Takže ta poslední patka pro písty je asi milimetr nad podložkou.  Zatím to ale nevidím jako problém, takže se tohle issue myslím může zavřít. :)

**Comment by kaklik** [comment]
Ukázalo se, že platforma zřejmě předpokládá uchycení na střechu takové, že dvě ramena budou symetricky dopředu a jedno rameno dozadu v ose auta. 
Takový předpoklad umístění je správně. 

Potíž ale je, že čtyři otvory šrouby nejsou v horní straně desky vzhledem k osám auta vyvrtány do čtverce, ale do kříže. 

Proto je potřeba otvory v prostředním dílu o 90 stupňů otočit, aby byla možná symetrická montáž.

**Comment by JanKott** [comment]
Otvory pro šrouby do desky na autě byly pootočeny o 15 stupňů kvuli konfliktu se šrouby mezi základnou a rameny. Odstranil jsem pootočení (takže teď jde dát platforma buď ramenem rovně dopředu, nebo dozadu). Posunul jsem díry na šrouby mezi základnou a rameny blíže k sobě (aby nebyly opět konfliktní). Díry na šrouby mezi základnou a rameny jsem navíc pootočil ve snaze změnit prohnutí spojených dílů směrem k desce na autě.

Je třeba přetisknout základnu a ramena (stl jsou aktualizované).

**Comment by kaklik** [comment]
Nová úprava základny funguje. :)

**Comment by ChroustJan** [comment]
Na začátku jsme neočekávali, že bude nutné platformu sundavat. Proto se ukázalo jako lepší řešení, mít šrouby umístěné trvale na střeše vozidla a platformu na ně pouze nandavat a z vrchu dotáhnout křídlovou maticí. Tento fakt vyžaduje změny dílu [888_4004](https://github.com/ThunderFly-aerospace/TF-R1/blob/24a9beb4cb99a7bc668c879a37c1d554b9eaf6eb/CAD/STL/888_4004.stl):

Je potřeba zespodu dílu v místě úchytných šroubů udělat kruhový otvor o průměru 19mm a výšce 10mm.  
![IMG_20190616_114029](https://user-images.githubusercontent.com/9783606/60493041-67b90f00-9cac-11e9-9b13-35a24f25ed0b.jpg)

Naopak ze shora je potřeba odstranit otvor na šestihrannou matici.  

Platforma pak bude z vrchní strany uchycena křídlovými maticemi, kterými se platforma přitáhne na šrouby pevně utažené maticemi do desky na střeše auta.

**Comment by JanKott** [comment]
Nakonec jsem kvůli konfliktům se šrouby do ramen nechal 19mm x 2mm prostor pro podložku a nad ní prostor pro M6 matici. Z horní strany jsem odstrani otvor na matici.
