### ISSUE TITLE
Pohyblivá část šestiosé platformy

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#17]
Pohybující se část šestiosé platformy bude s písty spojená přes [kulová ložiska](https://cz.rs-online.com/web/p/kulove-kloubove-spojky/7124995/).  
Šrouby těchto ložisek musí být umístěny na kruhové kónickém kuželu. Úhel kónusu  musí odpovídat výšce pístů a poloměru spodní základny #14. 
K uchycení šroubů se předpokládá použití  čtvercových matic. 

Na pohybující části má být umístěn přídržný elektromegnet. 

Díl může vycházet z existujícího dílu https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/888_3006.stl

**Comment by kaklik** [comment]
Začal jsem s konstrukcí pohyblivého dílu 888_4005

![image](https://user-images.githubusercontent.com/1194177/57983355-26003c00-7a51-11e9-83a1-b52663258af0.png)

Stav návrhu tohoto dílu je následující

- [x] Otvory pro uchycení magnetu
- [ ] Nastavitelnost úhlu ke spodní základně
- [x] Otvory pro čvercové matice na zašroubování kulových kloubů
- [x] Zapuštění podložek pro dotažení šroubů kulových kloubů.

**Comment by kaklik** [comment]
- Zmenšit výšku otvorů pro čtvercové matice a zajistit, aby měly buď strop a nebo dno.  Aby bylo možné o něco matici opřít před zašroubováním šroubu
- Úchyt pro magnet posunout excentricky co nejvíce dopředu

**Comment by ChroustJan** [comment]
Propadla se matice u označené díry fixou na fotce. Nebylo potřeba příliš síly. Prověřit zda tam není málo materiálu.
![IMG_20190630_165619](https://user-images.githubusercontent.com/9783606/60492328-06447080-9cab-11e9-8a68-fa999987b797.jpg)

**Comment by roman-dvorak** [comment]
Za závitem kulového čepu byly vypilovány dvě plošky pro klíč 11 mm. To umožnilo dotáhnout i čepy pod magnetem.

![20190706_114411_HDR](https://user-images.githubusercontent.com/5196729/60761395-ad2c6200-a047-11e9-839f-6a250fb1a38a.jpg)

Na dno děr pro matice je potřeba vytvořit jedna plná vrstva, která zkvalitní tisk. Zároveň může vyřešit problém s propadnutím stěny.

**Comment by roman-dvorak** [comment]
Nad matky pro připevnění magnetu byla přidána plná vrstva pro lepší tisk. To by mělo vyřešit možné propadnutí matky. Upravený model není kvůli https://github.com/ThunderFly-aerospace/TF-R1/issues/26#issuecomment-508974320 vyrenderovaný.

Jinak po testu 6. 7. se zdá být tento díl funkční.
