### ISSUE TITLE
Magnetický držák na telemetrickou antétu

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-R1#18]
K magnetickému držáku pro anemometr s venturiho trubicí je potřeba vytvořit adaptér na telemtrickou anténu.

Adaptér by měl vypadat tak, že to bude takové "víčko", kde bude vnější závit pro zašroubování do existujícího držáku. Na dně bude mít díru pro přišroubování antény. Díra musí mít průměr 12 mm. Mělo by to mít ještě osazení, aby to nebylo možné úplně zatočit a bylo oproti čemu to dotáhnout. 

Existující držák.
https://github.com/MLAB-project/Modules/issues/16

**Comment by kaklik** [comment]
@JanKott  Vypadá to, že tvůj magnetický držák bude mít další variantu použití. :)

**Comment by kaklik** [comment]
Současné řešení vypadá takhle: 

![antena](https://user-images.githubusercontent.com/1194177/58564685-b139b880-822d-11e9-8dbc-a95527561312.jpg)

To víčko, které na závit toho sloupku pasuje je [tady](https://github.com/MLAB-project/Modules/blob/master/mechanical/WINDGAUGE03A/amf/WINDGAUGE_S01.stl).

**Comment by roman-dvorak** [comment]
@cesilko1 vidím nový commit. Je to už tak dodělané? :)

**Comment by roman-dvorak** [comment]
Díl je upravený a připravený k výrobě!
 _telemetry_antena_holder.scad_

**Comment by kaklik** [comment]
@cesilko1  Dost by mi usnadnilo práci, kdyby si ty [commity tagoval k issue](https://help.github.com/en/articles/closing-issues-using-keywords). Protože takhle musím ten commit najít a podívat se, jestli si při tom vyrenderoval i tiskový soubor.
