### ISSUE TITLE
Přehrávání zvuku v rádiu z palubního počítače

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-R1#19]
Je potřeba nějakým způsobem dostat zvuk z palubního počitače do rádia v autě. Zvuk by mělo být možné dostat do předního USB hubu (kam je připojen display) kde je, myslím, jack 3 mm výstup. 

Je to potřeba pro hlášeni airspeed z autopilota. #9 

@ChroustJan, myslíš, že by to šlo nějak vyřešit pomocí rádia, co je v autě?

**Comment by ChroustJan** [comment]
Myslím, že jsme se koukali a auto nemá vstup jack. Možné řešení by bylo FM vysílač.

**Comment by roman-dvorak** [comment]
FM vysílač má výhodu, že telemetrická audio data by bylo možné poslouchat ve všech autech v okolí bez závislosti na jejich (speciálním) vybavení. Tato data jsou užitečná jak pro řidice tážného auta tak pro pilota ale i další zúčastněné.

**Comment by kaklik** [comment]
@ChroustJan  myslíš, že bys mohl zkusit najít nějaký FM vysílač, který se ideálně nepřipojuje do cigaretového socketu, ale třeba do USB?

**Comment by ChroustJan** [comment]
@kaklik  zkus ještě něco hledat. Ale s tím USB to nevidím dobře. Je to v podstatě produkt do auta.

**Comment by kaklik** [comment]
Koupil jsem a otestoval FM vysílač, který problém řeší.
