### ISSUE TITLE
Vytvořit silový spoj 12V pro palubní  přístroje

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#2]
Je potřeba vytvořit extra vývod 12V do kufru a 12V k měniči na 230 V rovnou z pojistkové skříně.

**Comment by kaklik** [comment]
Vývod palubních 12V, by zřejmě měl vést pod sedadlo řidiče, kde bude semipermanentně umístěný měnič na 230V. Z měniče pak povede odbočka 12V ke trojici autozásuvek u zadních sedadel.  (Trojice autozásuvek asi může být přišroubována, nebo přilepena na prostřední plastový díl mezi sedadly)

Na místě spolujezdce by měl být v předním kaslíku umístěn výkonový vypínač.

**Comment by kaklik** [comment]
Vývod byl nakonec vyveden přímo z hlavní autobaterie.

**Comment by roman-dvorak** [comment]
Na zadní vývod je potřeba ještě přidělat nějaké 12V zásuvky, které bude možné používat např na dobíječku LiPol akumulátorů. Nebo jiných zařízení.

Mohlo by to vyřešit problém s bezpečnostním vypínáním nabíječky při poklesu napájení. Tento pokles může být způsoben dvojicí autozásuvek a tenkých vodičů.

**Comment by kaklik** [comment]
Za tímto účelem by zřejmě bylo vhodné upravit krabičku pro rozvody a zásuvky tak, aby v ní byl rovnou zabudován displej indikátoru palubního napětí.  #12

**Comment by JakubMares96** [comment]
@roman-dvorak Mohl bych poprosit zda jsou někde dostupné rozměry použitého displeje?

**Comment by kaklik** [comment]
@ChroustJan  by snad měl mít ten idikátor nějak u sebe. Nebo alespoň vědět jak vypadá.

**Comment by ChroustJan** [comment]
@JakubMares96 počítej s tím, že indikátor v krabičce potřebuje obdélníkový otvor a definovanou tloušťku materiálu, do kterého se zacvakává. Přesné rozměry pak musím přeměřit. Ale pro představu je to něco jako 5,5x3,5cm, ale to beru hodně od oka.

**Comment by kaklik** [comment]
Vyřešeno instalací rozvodné krabičky.
