### ISSUE TITLE
Překabelování palubního LCD

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-R1#23]
Protože iTec externí dokovací stanice používá pro HDMI nějaký nestandartní driver a rozfugování HDMI na Ubuntu je velmi složité (Může to být způsobeno hromadou dalších věcí - jako nekvalitní USB kabely)

Lenovo dokovací stanice obsahuje 2 grafické výstupy - VGA a DisplaPort (větší varianta). Je potřeba otestovat, jestli by fugovalo řešení DP - HDMI adaptér a cca 2 M HDMI kabelu. Dokovací stanice může pod rádiem zůstat pro napájení LCD displaye a případné připojení nějakého externího zařízení. Např joystick s touchapadem na ovládání displaye.

**Comment by ChroustJan** [comment]
@roman-dvorak @kaklik máme 2m HDMI kabel?

**Comment by ChroustJan** [comment]
Co tohle: https://www.czc.cz/premiumcord-displayport-na-hdmi-kabel-3m-m-m/107590/produkt?gclid=CjwKCAjwuqfoBRAEEiwAZErCsuYA8Q81aUNjG2vzRIIeWnssioN1tVSdL1iPgU9vKe4HCrL3581O6RoCSEMQAvD_BwE

**Comment by kaklik** [comment]
Tohle má dlouhej HDMI konektor, který bude trčet do boku z toho dispeleje.

**Comment by roman-dvorak** [comment]
Také by byla varianta pouze sehnat HDMI prodlužovák a DP-HDMI redukci. U
displaye použít ten ohnutý HDMI, co máme.

Jen nevím, jestli ten ohnutý HDMI není na straně u rovného konektoru nějaké
trošku zlomený. Protože když jsem s ním hýbal u sebe v notebooku, tak
display trošku měnil barvy... (Myslel jsem, že tohle v době HDMI nejde a
byla to vlastnost pouze VGA :D )


Dne čt 20. 6. 2019 9:45 uživatel Jakub Kákona <notifications@github.com>
napsal:

**Comment by roman-dvorak** [comment]
Na tento test jsem našel, že mám:
 - DP - HDMI (F) redukce
 - HDMI - HDMI kabel (asi 2m)
 - DP - HDMI kabel (2 m)

Takže navrhuji to nejdříve zkusit s tímto. A následně se rozhodnout o dalším použití
Přední USB hub bude využit pro napájení LCD a připojení dalších periferií (zvuk, joystick s touchpadem, ...) Zatím se budeme muset vyrovnat s tím, že HDMI kabel bude trčet s displaye. To vyřešíme následně.

a také potřebnou redukci z SMA-R na SMA.

**Comment by roman-dvorak** [comment]
LCD display funguje s 2M DP - HDMI kabeleme
