### ISSUE TITLE
Přidání wifi AP

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#24]
Pro spojení více vnějších zařízení k MAVLink síti by bylo potřeba mít v autě wifi AP. 
Na střeše auta by zřejmě měla být přídavná anténa pro připojení externích zařízení.

**Comment by roman-dvorak** [comment]
Při dnešním testu se sektorovou anténou na startovacím autě a všesměrovou na druhém autě se ukázalo jako použitelné řešení pro routování mavlinku. 

Toto by bylo možné vylepšit použitím jiného AP (se switchem) a ideálně možností více antét. Všesměrová a sektorová. 

Použití pouze všesměrové antény přináši problém, že se startovací auto nesmí otočit od druhého.
