### ISSUE TITLE
Nahrávání zvuku při testech na střeše auta

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-R1#25]
Je potřeba zjistit, jestli není možné nějakým způsobem ke kamerám přímo připojit mikrofon. Popřípadě mikrofon prokabelovat přímo do zvukovky PC a zaznamenávat je zároveň se záznamem z kamery ve VLC (#5)

Zvuk může posloužit jako dobrý diagnostický prostředek.

**Comment by kaklik** [comment]
Bylo vyřešeno naletováním mikrofonu do IP kamery.
