### ISSUE TITLE
Opravit popřípadě vyřešit napájení palubního počítače z 12V

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-R1#31]
12V zdroj z číny přestal fugovat. Po jeho rozebrání bylo zjištěno, že v konektoru není 10k odpor, který by měl zajišťovat selekci maximálního výkonu dodaného zdrojem. Podle některých příspěvků (převážně na fórech) nekonečný odpor znamená 90W zdroj. Se zařazením 10k odporu by to mělo odpovídat 65W zdroji. 

Např tady: [http://forum.notebookreview.com/threads/thinkpad-adapter-resistor-values.681124/](http://forum.notebookreview.com/threads/thinkpad-adapter-resistor-values.681124/)

**Comment by kaklik** [comment]
Vyřešeno integrací zdroje přímo do rozvodné krabice zásuvek.
