### ISSUE TITLE
Montáž kamery do základny šestiosé platformy

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#32]
Do kruhové části šestiosé platformy by bylo potřeba přidat USB kameru, která bude zespodu sledovat pohyblivou část platformy. 

Typ kamery je [DMM-1118](http://www.vast-tech.com.tw/en/product_detail.php?PKey=34#menu2). Minimální průměr otvoru pro objektiv je 15 mm. Montáž je vhodné provést šrouby M2 v rozích kamery.

**Comment by roman-dvorak** [comment]
Ze spodu horní (Pohyblivé) části by bylo vhodné nalepit nějaký dvojrozměrný čárový kód optimalizovaný pro snadné počítačové vyhledávání.

**Comment by kaklik** [comment]
To ano, ale teď ve vůbec problém, aby někdo do platformy doplnil ten montážní otvor na kameru.
