### ISSUE TITLE
Upevnění hadice k výdechu ventilace auta - Yaris

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-R1#38]
Baterie vírníku je potřeba při teplotach pod 10°C vyhřívat. Jeden z možných způsobů je dovést teplý vzduch z ventilace auta pod samotný trup vírníku. 

Na následujících obrázcích je navrhované umístění hadice.

![20191118_171935](https://user-images.githubusercontent.com/5196729/69260173-c16c9800-0bbf-11ea-8e33-4278dbb73d17.jpg)

Hadice (o vnitřním průměru 60 mm) by na svém konci měla mít kruhový nástavec, který dosedne na kruhový výduch. 
![20191118_171841](https://user-images.githubusercontent.com/5196729/69260418-27591f80-0bc0-11ea-9200-72e468687781.jpg)

Na hadici by o cca 5 cm níže měla být další objímka, která na své spodní straně bude místo pro nalepení suchého zipu. Druhá část zipu bude nalepena v "žlabu" výdechu. 

![20191118_171858](https://user-images.githubusercontent.com/5196729/69260697-933b8800-0bc0-11ea-8c70-718d30618f33.jpg)

Hodice by mezi límcem k výdechu a suchým zipem měla být zmáčknuta. Tím dojde k domáčknutí límce k výdechu.

**Comment by kaklik** [comment]
Tady je trochu nakresleno, jak to @roman-dvorak  myslel. 

![image](https://user-images.githubusercontent.com/1194177/70646253-cf558c00-1c46-11ea-8100-5b5e1f590d71.png)

Celá konstrukce jsou dva tištěné kroužky s vnitřním závitem našroubované na hadici. 
První kroužek vlevo má za cíl zarovnat hrdlo hadice tak, aby doléhalo na výstup výdechu auta.  Druhý kroužek našroubovaný na hadici o něco dále slouží k uchycení hadice suchým zipem na palubní desku auta. (jeden kus suchého zipu bude nalepený na kroužku na hadici a druhý kus na palubní desce)

Mezi prvním a druhým kroužkem bude reálně max 10 závitů (oproti obrázku)

**Comment by kaklik** [comment]
@JanKott  začal s tvorbou modelu kroužku pro uchycení hadice.

![obrazek](https://user-images.githubusercontent.com/1194177/72000784-54cb5c80-3244-11ea-9f1b-6d6967f65c6e.png)

Zdrojový soubor jsem [přidal](https://github.com/ThunderFly-aerospace/TF-R1/blob/master/CAD/src/hose_adapter.scad) do repositáře.

**Comment by roman-dvorak** [comment]
Tohle bych v aktuálnímu stavu viděl jako nepotřebné. První let s TF-G1 bude na jaře v létě (v teple)
