### ISSUE TITLE
Do držáku wifi antény se nevejde všesměrová wifi anténa

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#39]
Průměr všesměrových wifi antén je u paty 13mm, nikoliv 12mm na které je zřejmě dimenzován model.

**Comment by roman-dvorak** [comment]
Vyřešeno.

**Comment by kaklik** [comment]
Anténa po zvětšení otvoru pasuje. Matice šroubu nyní vyčuhuje z plastu směrem k anténě.  Řešení je však aktuálně použitelné.
