### ISSUE TITLE
Zamlžování kamer

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#4]
Do palubních kamer na střeše zřejmě prosakuje voda protože se zamlžují. 
Řešení asi je do obalu vhodně udělat odvětrávací dírku, aby případná vlhkost měla kudy uniknout z obalu kamery.

**Comment by kaklik** [comment]
@roman-dvorak Zjistil že u IP kamer lze "zapnout vyhřívání".

**Comment by roman-dvorak** [comment]
Chtělo by to zjistit, jestli tuto funkci mají obě kamery. V nastavení (přes webové rozhraní) je to pojmenované jako 'Defrosting" a lze tomu nastavit nějaká hodnota 0-100. V zapnutém stavu je to docela znát.

**Comment by kaklik** [comment]
@roman-dvorak To musíme vyzkoušet na té kameře na autě, teď k ní není přístup. Jak se do toho webového rozhraní kamery dostaneš bez windows a IE?

**Comment by roman-dvorak** [comment]
@kaklik Ano, musel jsem si znovu-rozfungovat windows a z IE s nějakým pluginem jsem se do toho rozhraní dostal. To můžeme vyzkoušet na kameře na autě.

**Comment by kaklik** [comment]
Vyřešeno vysušením kamery a  vložením pytlíku se silicagelem.

**Comment by roman-dvorak** [comment]
Zadní kamera se znovu zamlžovala. Byla na nějkou dobu otevřena a vyvětrána. Bylo znát, že vyhřívání funguje. Což zřejme způsobilo vypaření vlhkosti a zkondenzování na vnitřní straně průhledné koupulky.

**Comment by kaklik** [comment]
Možná by bylo řešením kamery nechat trvale připojené a tím i zahřáté na provozní teplotu.
