### ISSUE TITLE
Instalace palubního počítače

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-R1#7]
@ChroustJan  pořídí [palubní počítač](https://www.levne-notebooky-pc.cz/black-friday/profesionalni-notebook-s-core-i5-lenovo-thinkpad-t430) s [dokovací stanicí](https://www.superlevnapc.cz/ibm-4337-lenovo-thinkpad-mini-dock-series-3-usb-3-0-vcetne-klicu.html). 

Bude na něj potřeba nainstalovat OS a potřebné nástroje: 

- Ubuntu 18.04 (Desktop), naistaluje @kaklik paralelně se zachováním naistlavoných windows
- ROS nainstaluje @roman-dvorak 
- Qgroudcontrol server pro připojení QGC klienta - zde je trochu komplikace neboť zatím není jasné, jak lze vytvořit telemetrický server.

**Comment by roman-dvorak** [comment]
Jako QGroundControl server by měla sloužit utilita `mavproxy.py`,  která se připojí na sériovku a vytváří UDP rozhraní. Zatím mi nefunguje úplně dobře. Po spuštění QGC se k mavproxy neustále připojuje a odpojue. Mavproxy vypadá připojené stále....

Zkusil jsem napsat, na jejich fórum jaké je nejlepší řešení. Tak počkám na odpovědi.

**Comment by roman-dvorak** [comment]
Na foru mi bylo doporučeno toto: [mavlink-router](https://github.com/intel/mavlink-router). Po prvním otestování lokálně na PC se zdá, že by to mohlo fungovat. Instalace proběhla podle postupu na GitHubu bez problému.

Spuštění pak pomocí příkazu
`mavlink-routerd -e 0.0.0.0:14550 /dev/ttyACM1`

**Comment by roman-dvorak** [comment]
V autě bylo nějakou dobu experimentováno s přenosem MAVLINKU přes MAVROS. Mělo to velmi špatnou spolehlivost a bylo to extrémně snadné rozbít - někdy ani nevím jak. Proto navrhuji pokusit se vrátit k mavlink routeru, který bude Mavlink z modemu překládat na UDP.  To budou poslouchat jednotliví klienti.

**Comment by kaklik** [comment]
Routování mavlinku funguje.
